### ISSUE TITLE
Activity entity generates an error. 

### ISSUE THREAD

**Issue by koenvb** [ITLec/PowerQueryBuilder#7]
When trying to generate a fetch XML view for the activity entity I  get the following error:
```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at ITLec.ChartGuy.PowerQueryBuilder.PowerQueryAttribute.GetPowerQueryAttributeByMetadata(AttributeMetadata attribute)
   at ITLec.ChartGuy.PowerQueryBuilder.MainForm.UpdateFetchXmlListView()
   at ITLec.ChartGuy.PowerQueryBuilder.MainForm.tsbUpdateFetchXml_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

I had no issues generating the fetch XML for quotes / Leads/ Opportunities? 

![activity_entity](https://user-images.githubusercontent.com/76891/42502920-93b624d2-8437-11e8-8ebc-718e6c12760d.png)

Not sure what would cause the issue. Restarting XrmToolbox does not work. 

* XrmToolbox v 1.2018.6.25
* Power Query builder v 1.2018.7.7

**Comment by koenvb** [comment]
Confirmed working on new release
XrmToolbox:  v 1.2018.7.27
Power Query: v 1.2018.7.20
